### ISSUE TITLE
Prism does not honor over-ridden highlights in vimrc

### ISSUE THREAD

**Issue by justrajdeep** [UncleBill/prism.vim#2]
Hi 

I am trying to override the `StatusLine` of a colorscheme from my `vimrc` like as below. It works if i dont use prism, but with prism it is not getting picked up.

    hi StatusLine guifg=black guibg=#d7afff ctermfg=black ctermbg=magenta
    hi StatusLineNC guifg=black guibg=#8fbfdc ctermfg=black ctermbg=cyan

Please look into this. Thanks for this nice plugin.

**Comment by UncleBill** [comment]
Hi @justrajdeep, these two hightlighting groups might be overridden by the new setting colorscheme. Upgrading to the newsest plugin, then adding following code to your vimrc should resolve the problem:

```vim
function! SetStatusLine() abort
  hi StatusLine guifg=black guibg=#d7afff ctermfg=black ctermbg=magenta
  hi StatusLineNC guifg=black guibg=#8fbfdc ctermfg=black ctermbg=cyan
endfunction
autocmd ColorScheme * call SetStatusLine()
```

**Comment by justrajdeep** [comment]
hi @UncleBill 

I tried this, with [solarized](https://github.com/altercation/vim-colors-solarized). It did not take effect. Am i missing something?

**Comment by UncleBill** [comment]
Well, checking out `:verbose hi StatusLine`, we can see `solarized` set `gui=reverse`, so the colors are reversed. You can add `gui=NONE` to the hightlighting attributes.

![image](https://user-images.githubusercontent.com/1141198/97824372-ade60e80-1cf6-11eb-9b12-64843d5e15dd.png)


```vim
function! SetStatusLine() abort
  hi StatusLine guifg=black guibg=#d7afff ctermfg=black ctermbg=magenta gui=NONE
  hi StatusLineNC guifg=black guibg=#8fbfdc ctermfg=black ctermbg=cyan gui=NONE
endfunction
autocmd ColorScheme * call SetStatusLine()
```

**Comment by justrajdeep** [comment]
Thanks for the prompt response ... it works 👍
